added vos support
CosmoStat/cs_util pull request #8
Opened 2023-01-04 10:39 UTC by martinkilbinger

vos (Virtual Observatory Software) is added, copied from copied from shapepipe/utilities/canfar.py with minor modifications.

Basic unit tests are implemented.

Closes #7 .

2023-02-15 16:46 UTC, sfarrens requested changes

2023-02-15 16:46 UTC, sfarrens commented on cs_util/tests/test_canfar.py
> +
```suggestion
```

2023-02-15 16:46 UTC, sfarrens commented on cs_util/canfar.py
> +    vls_out : array of str
check data type

2023-02-15 16:46 UTC, sfarrens commented on cs_util/canfar.py
> +    import_fail = False
So, it appears from the `requirements.txt` that `vos` is not an optional dependency. This `try/except` structure at the import level would imply that it is optional. I would suggest you either leave this and remove `vos` from the requirements or make this a direct import. If you go for the former, see my comment below for the corresponding unit test.

2023-02-15 16:46 UTC, sfarrens commented on cs_util/tests/test_canfar.py
> +        vos = canfar.vosHandler(self._cmd_ok)
If `vos` is left as an optional dependency, I believe this will raise an error if `vos` is not installed (from the `self._check_vos_install()` in the `__init__`). You may want to consider adding a `@skifUnless` or `@skifIf` decorator to this test (see e.g. [ModOpt](https://github.com/CEA-COSMIC/ModOpt/blob/master/modopt/tests/test_math.py#L45)).

If `vos` is made a requirement then ignore this comment.

2023-02-15 16:47 UTC, sfarrens commented
Hi @martinkilbinger nice implementation! Just a few minor things to fix in my opinion.

2023-02-15 18:04 UTC, martinkilbinger commented on cs_util/canfar.py
> +    vls_out : array of str
changed.

2023-02-15 19:11 UTC, martinkilbinger commented on cs_util/canfar.py
> +    import_fail = False
Changed, try/except removed, it should not be optional.

2023-02-16 08:54 UTC, sfarrens commented on cs_util/canfar.py
> +    import_fail = False
Did you push these changes? I don't see them.

2023-02-16 09:55 UTC, martinkilbinger commented on cs_util/canfar.py
> +    import_fail = False
ah, I forgot, it's pushed now.

2023-02-16 12:23 UTC, sfarrens approved these changes

2023-02-16 12:26 UTC, merged